--check all the data is load properly
select 
count(*)
from Retail_Sales

--explore all object in the database

select*
from INFORMATION_SCHEMA.TABLES

--explore all columns in the database
select*
from INFORMATION_SCHEMA.COLUMNS


--check the null value and then delete

select* 
from Retail_Sales
where transactions_id is null 
or sale_date is null 
or sale_time is null
or gender is null
or category is null
or quantiy is null
or total_sale is null
or cogs is null
or price_per_unit is null
or age is null

delete from Retail_Sales
where transactions_id is null 
or sale_date is null 
or sale_time is null
or gender is null
or category is null
or quantiy is null
or total_sale is null
or cogs is null
or price_per_unit is null

-- check duplicate

select
transactions_id,
count(*)
from Retail_Sales
group by transactions_id
having count(*)>1

--explore all the unique customer_id

select 
distinct customer_id
from Retail_Sales

--explore all the categories

select
distinct category
from Retail_Sales

--find the date of the first sale and last sale

select
min(sale_date) as first_sale_date,
max(sale_date) as last_sale_date,
DATEDIFF(month,min(sale_date),max(sale_date)) as sales_range_month
from Retail_Sales

--find the youngest and oldest customer

select
min(age) as youngest_customer_age,
max(age) as oldest_customer_age
from Retail_Sales

--generate the report that shows all key metrics of the business

select 'total_sales' as measure_name,sum(total_sale) as measure_value from Retail_Sales
union all
select 'total_quantity',sum(quantiy) from Retail_Sales
union all
select 'avg_price',avg(price_per_unit) from Retail_Sales
union all
select 'total_cogs',sum(cogs) from Retail_Sales
union all
select 'avg_cogs',avg(cogs) from Retail_Sales
union all
select 'total_customers',count(distinct customer_id) from Retail_Sales

--total revenue generated by customer

select
customer_id,
sum(total_sale) as total_revenue
from Retail_Sales
group by customer_id
order by total_revenue desc

--total revenue generated by each category

select
category,
sum(total_sale) as total_revenue_category
from Retail_Sales
group by category
order by total_revenue_category desc

--total number of purchase by customer

select
customer_id,
count(customer_id) as total_purchase
from Retail_Sales
group by customer_id
order by total_purchase desc

--total revenue generated by each gender

select
gender,
sum(total_sale) as revenue_by_gender
from Retail_Sales
group by gender

--avg cogs in each category

select
category,
avg(cogs) as avg_cog_category
from Retail_Sales
group by category

--avg price by each category

select
category,
avg(price_per_unit) as avg_price_category
from Retail_Sales
group by category

---what is the distribuation of sold items by category

select
category,
sum(quantiy) as total_sold_items
from Retail_Sales
group by category
order by total_sold_items asc

--total_number of transaction made by each gender

select
customer_id,
count(transactions_id) as total_transactions
from Retail_Sales
group by customer_id
order by total_transactions desc

--average sales of each month and find out best selling month in each year

select
months,
years,
avg_sale
from
	(select
	datename(month,sale_date) as months,
	year(sale_date) as years,
	avg(total_sale) as avg_sale,
	rank() over (partition by year(sale_date) order by avg(total_sale) desc) as rank
	from Retail_Sales
	group by datename(month,sale_date),year(sale_date)
    )t
where rank=1


--3 customer with the fewest purchases

select top 3
customer_id,
count(*) as total_purchase
from Retail_Sales
group by customer_id
order by total_purchase asc

--top 5 customer with the higest revence

select top 5
customer_id,
sum(total_sale) as total_sales
from Retail_Sales
group by customer_id
order by total_sales desc


--end of project